# escape=`

FROM node:14-alpine as deps

WORKDIR /app

COPY package*.json .

RUN npm install

FROM node:14-alpine as build

WORKDIR /app

COPY --from=deps /app/node_modules /node_modules

COPY . .

RUN npm run build

FROM nginx:1.21.0-alpine as production

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]